DEPLOYED=false
URL=https://sys2.roneu.dk
PORT=9292

//DB
CONNECTION_STR=jdbc:postgresql://db_2sem:5432/
DB_NAME=alpha
DB_USERNAME=postgres
DB_PASSWORD=postgres

//JWT
ISSUER=4SEMSYSAALOT
TOKEN_EXPIRE_TIME=86400000
SECRET_KEY=supersecretkey12345678901234567890

##Mail
#The mail system is uses a BREVO_API_KEY key (Ask Oliver for API key if you haven't gotten it.)
email.sender=cph-om96@stud.ek.dk

# SMTP (Does not work with Digital Ocean)
#smtp.host = Your_SMTP_SERVER
#smtp.port = port_ip
