DEPLOYED=false
BACKEND_URL=https://standflow.api.roneu.dk
FRONTEND_URL=https://standflow.roneu.dk
PORT=9393

//DB
CONNECTION_STR=jdbc:postgresql://db_2sem:5432/
DB_NAME=standflow
DB_USERNAME=postgres
DB_PASSWORD=postgres

//JWT
ISSUER=AIDASTANDFLOW
TOKEN_EXPIRE_TIME=86400000
SECRET_KEY=supersecretkey12345678901234567890

